CREATE TABLE MONTADORA (
	MONT_ID SERIAL PRIMARY KEY NOT NULL,
	NOME TEXT NOT NULL,
	PAIS TEXT NOT NULL,
	ANO_FUNDACAO INT NOT NULL
)

--(id: ULID, nome: string, pais: string, ano_fundacao: int)


-- (id: ULID, nome: string, montadora_id: string, valor_referencia: number, 
-- motorizacao: number, turbo: boolean, automatico: boolean)

CREATE TABLE MODELO_VEICULO (
	MOD_ID SERIAL PRIMARY KEY NOT NULL,
	NOME TEXT NOT NULL,
	MONT_ID INT NOT NULL REFERENCES MONTADORA(MONT_ID),
	VALOR_REFERENCIA DECIMAL(10, 2) NOT NULL,
	MOTORIZACAO INT NOT NULL,
	TURBO BOOLEAN NOT NULL,
	AUTOMATICO BOOLEAN NOT NULL,
	FOREIGN KEY (MONT_ID) REFERENCES MONTADORA(MONT_ID) ON DELETE CASCADE
)

--(id: ULID, modelo_id: string, cor: string, ano_fabricacao: number, 
-- ano_modelo: number, valor: number, placa: string, vendido: boolean)

CREATE TABLE VEICULO (
	VEIC_ID SERIAL PRIMARY KEY NOT NULL,
	MOD_ID INT NOT NULL REFERENCES MODELO_VEICULO(MOD_ID),
	COR TEXT NOT NULL,
	ANO_FABRICACAO INT NOT NULL,
	ANO_MODELO INT NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
	PLACA TEXT NOT NULL,
	VENDIDO BOOLEAN NOT NULL,
	FOREIGN KEY (MOD_ID) REFERENCES MODELO_VEICULO(MOD_ID) ON DELETE CASCADE
)

INSERT INTO MONTADORA VALUES (DEFAULT, 'TOYOTA', 'JAPÃO', 1920)
INSERT INTO MODELO_VEICULO VALUES (DEFAULT, 'MODELO1', 1, 30000.00, 1, TRUE, TRUE)
INSERT INTO VEICULO VALUES (DEFAULT, 1, 'VERMELHO', 2024, 1, 30500.00, 'AAAA', FALSE)